# Generated by Django 5.0.6 on 2026-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
