# Generated by Django 5.0.6 on 2026-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('story_type', models.CharField(choices=[('beneficiary', 'Beneficiary Story'), ('volunteer', 'Volunteer Story'), ('partner', 'Partner Story'), ('supporter', 'Supporter Story'), ('community', 'Community Story')], default='beneficiary', max_length=30)),
                ('short_quote', models.CharField(max_length=255)),
                ('full_story', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stories/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
