# Generated by Django 5.0.6 on 2026-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_story', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField(help_text='You can write values as one paragraph or short sentences.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
